using System.Text.RegularExpressions;
namespace DeveloperBrowser.Core.Collections;
public sealed record SavedRequestField(bool IsEnabled, string Key, string? Value);
public sealed class SavedRestRequest { public Guid Id { get; set; } = Guid.NewGuid(); public Guid CollectionId { get; set; } public Guid? FolderId { get; set; } public required string Name { get; set; } public string? Description { get; set; } public required string Method { get; set; } public required string Url { get; set; } public List<SavedRequestField> Parameters { get; set; } = []; public List<SavedRequestField> Headers { get; set; } = []; public string Body { get; set; } = string.Empty; public string ContentType { get; set; } = "application/json"; public string AuthType { get; set; } = "None"; public string? AuthToken { get; set; } public string? AuthUsername { get; set; } public string? AuthPassword { get; set; } public int SortOrder { get; set; } public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class RestCollection { public Guid Id { get; init; } = Guid.NewGuid(); public required string Name { get; set; } public string? Description { get; set; } public int SortOrder { get; set; } public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; public List<RestCollectionFolder> Folders { get; set; } = []; public List<SavedRestRequest> Requests { get; set; } = []; }
public sealed class RestCollectionFolder { public Guid Id { get; init; } = Guid.NewGuid(); public Guid CollectionId { get; set; } public Guid? ParentFolderId { get; set; } public required string Name { get; set; } public int SortOrder { get; set; } public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class RestEnvironment { public Guid Id { get; init; } = Guid.NewGuid(); public required string Name { get; set; } public string? Description { get; set; } public string Color { get; set; } = "#4ADE80"; public bool IsActive { get; set; } public int SortOrder { get; set; } public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; public List<RestEnvironmentVariable> Variables { get; set; } = []; }
public sealed class RestEnvironmentVariable { public Guid Id { get; init; } = Guid.NewGuid(); public Guid EnvironmentId { get; set; } public required string Key { get; set; } public string? Value { get; set; } public string? Description { get; set; } public bool IsSecret { get; set; } public bool IsEnabled { get; set; } = true; public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public interface ICollectionService { Task<IReadOnlyList<RestCollection>> GetCollectionsAsync(CancellationToken cancellationToken = default); Task<RestCollection> CreateCollectionAsync(string name, string? description = null, CancellationToken cancellationToken = default); Task RenameCollectionAsync(Guid id, string name, CancellationToken cancellationToken = default); Task UpdateCollectionAsync(Guid id, string name, string? description, CancellationToken cancellationToken = default); Task DeleteCollectionAsync(Guid id, CancellationToken cancellationToken = default); Task<RestCollectionFolder> CreateFolderAsync(Guid collectionId, string name, Guid? parentFolderId = null, CancellationToken cancellationToken = default); Task RenameFolderAsync(Guid id, string name, CancellationToken cancellationToken = default); Task DeleteFolderAsync(Guid id, CancellationToken cancellationToken = default); Task<SavedRestRequest> SaveRequestAsync(SavedRestRequest request, CancellationToken cancellationToken = default); Task DeleteRequestAsync(Guid id, CancellationToken cancellationToken = default); Task<SavedRestRequest> DuplicateRequestAsync(Guid id, CancellationToken cancellationToken = default); Task MoveRequestAsync(Guid id, Guid collectionId, Guid? folderId, CancellationToken cancellationToken = default); Task<IReadOnlyList<SavedRestRequest>> SearchAsync(string query, CancellationToken cancellationToken = default); }
public interface IEnvironmentService { Task<IReadOnlyList<RestEnvironment>> GetEnvironmentsAsync(bool includeSecretValues = false, CancellationToken cancellationToken = default); Task<RestEnvironment> CreateEnvironmentAsync(string name, string? description = null, string? color = null, bool makeActive = false, CancellationToken cancellationToken = default); Task RenameEnvironmentAsync(Guid id, string name, string? description, CancellationToken cancellationToken = default); Task SetActiveAsync(Guid? id, CancellationToken cancellationToken = default); Task<RestEnvironment> DuplicateEnvironmentAsync(Guid id, CancellationToken cancellationToken = default); Task DeleteEnvironmentAsync(Guid id, CancellationToken cancellationToken = default); Task<RestEnvironmentVariable> SaveVariableAsync(RestEnvironmentVariable variable, CancellationToken cancellationToken = default); Task DeleteVariableAsync(Guid id, CancellationToken cancellationToken = default); }
public sealed record VariableResolution(string Value, IReadOnlyList<string> MissingVariables) { public bool IsResolved => MissingVariables.Count == 0; }
public interface IVariableResolver { VariableResolution Resolve(string? template, IReadOnlyDictionary<string, string> values); }
public sealed class VariableResolver : IVariableResolver { private static readonly Regex Pattern = new(@"\{\{\s*([A-Za-z_][A-Za-z0-9_.-]*)\s*\}\}", RegexOptions.Compiled); public VariableResolution Resolve(string? template, IReadOnlyDictionary<string, string> values) { var missing = new HashSet<string>(StringComparer.OrdinalIgnoreCase); var result = Pattern.Replace(template ?? string.Empty, m => { var key = m.Groups[1].Value; if (values.TryGetValue(key, out var value)) return value; missing.Add(key); return m.Value; }); return new(result, missing.OrderBy(x => x, StringComparer.OrdinalIgnoreCase).ToArray()); } }
public sealed record CollectionExport(string Format, int Version, RestCollection Collection);
public interface ICollectionImportExportService { Task<string> ExportAsync(Guid collectionId, bool includeSensitiveValues, CancellationToken cancellationToken = default); Task<RestCollection> ImportAsync(string json, CancellationToken cancellationToken = default); }
