using System.Text.Json;
using DeveloperBrowser.Core.Collections;
using DeveloperBrowser.Core.Security;
using DeveloperBrowser.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace DeveloperBrowser.Infrastructure.Collections;

public sealed class LocalCollectionService(IDbContextFactory<DeveloperBrowserDbContext> factory) : ICollectionService
{
    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    private async Task<DeveloperBrowserDbContext> Db(CancellationToken ct) { var db = await factory.CreateDbContextAsync(ct); await db.Database.EnsureCreatedAsync(ct); await CollectionSchema.EnsureAsync(db, ct); return db; }
    public async Task<IReadOnlyList<RestCollection>> GetCollectionsAsync(CancellationToken ct = default) { await using var db = await Db(ct); var collections = await db.Collections.OrderBy(x => x.SortOrder).ThenBy(x => x.Name).ToListAsync(ct); var folders = await db.CollectionFolders.ToListAsync(ct); var requests = await db.SavedRequests.OrderBy(x => x.SortOrder).ThenBy(x => x.Name).ToListAsync(ct); return collections.Select(c => ToModel(c, folders.Where(x => x.CollectionId == c.Id), requests.Where(x => x.CollectionId == c.Id))).ToArray(); }
    public async Task<RestCollection> CreateCollectionAsync(string name, string? description = null, CancellationToken ct = default) { name = Required(name, 160); await using var db = await Db(ct); var item = new CollectionEntity { Name = name, Description = Trim(description, 1000), SortOrder = await db.Collections.CountAsync(ct) }; db.Collections.Add(item); await db.SaveChangesAsync(ct); return ToModel(item, [], []); }
    public async Task RenameCollectionAsync(Guid id, string name, CancellationToken ct = default) { await using var db = await Db(ct); var item = await db.Collections.FindAsync([id], ct) ?? throw new InvalidOperationException("Collection not found."); item.Name = Required(name, 160); item.UpdatedAt = DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); }
    public async Task UpdateCollectionAsync(Guid id, string name, string? description, CancellationToken ct = default) { await using var db = await Db(ct); var item = await db.Collections.FindAsync([id], ct) ?? throw new InvalidOperationException("Collection not found."); item.Name = Required(name, 160); item.Description = Trim(description, 1000); item.UpdatedAt = DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); }
    public async Task DeleteCollectionAsync(Guid id, CancellationToken ct = default) { await using var db = await Db(ct); db.SavedRequests.RemoveRange(db.SavedRequests.Where(x => x.CollectionId == id)); db.CollectionFolders.RemoveRange(db.CollectionFolders.Where(x => x.CollectionId == id)); var collection = await db.Collections.FindAsync([id], ct); if (collection is not null) db.Collections.Remove(collection); await db.SaveChangesAsync(ct); }
    public async Task<RestCollectionFolder> CreateFolderAsync(Guid collectionId, string name, Guid? parentFolderId = null, CancellationToken ct = default) { await using var db = await Db(ct); if (!await db.Collections.AnyAsync(x => x.Id == collectionId, ct)) throw new InvalidOperationException("Collection not found."); var item = new CollectionFolderEntity { CollectionId = collectionId, ParentFolderId = parentFolderId, Name = Required(name, 160), SortOrder = await db.CollectionFolders.CountAsync(x => x.CollectionId == collectionId, ct) }; db.CollectionFolders.Add(item); await db.SaveChangesAsync(ct); return new() { Id = item.Id, CollectionId = item.CollectionId, ParentFolderId = item.ParentFolderId, Name = item.Name, SortOrder = item.SortOrder, CreatedAt = item.CreatedAt, UpdatedAt = item.UpdatedAt }; }
    public async Task RenameFolderAsync(Guid id, string name, CancellationToken ct = default) { await using var db = await Db(ct); var item = await db.CollectionFolders.FindAsync([id], ct) ?? throw new InvalidOperationException("Folder not found."); item.Name = Required(name, 160); item.UpdatedAt = DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); }
    public async Task DeleteFolderAsync(Guid id, CancellationToken ct = default) { await using var db = await Db(ct); var folders = await db.CollectionFolders.ToListAsync(ct); var toDelete = new HashSet<Guid> { id }; var queue = new Queue<Guid>(); queue.Enqueue(id); while (queue.TryDequeue(out var parentId)) foreach (var child in folders.Where(folder => folder.ParentFolderId == parentId)) if (toDelete.Add(child.Id)) queue.Enqueue(child.Id); db.SavedRequests.RemoveRange(db.SavedRequests.Where(request => request.FolderId.HasValue && toDelete.Contains(request.FolderId.Value))); db.CollectionFolders.RemoveRange(folders.Where(folder => toDelete.Contains(folder.Id))); await db.SaveChangesAsync(ct); }
    public async Task<SavedRestRequest> SaveRequestAsync(SavedRestRequest request, CancellationToken ct = default) { Validate(request); await using var db = await Db(ct); var existing = await db.SavedRequests.FindAsync([request.Id], ct); if (existing is null) { existing = new SavedRequestEntity { Id = request.Id, CreatedAt = request.CreatedAt, Name = request.Name, Method = request.Method, Url = request.Url }; db.SavedRequests.Add(existing); } Copy(request, existing); await db.SaveChangesAsync(ct); return ToModel(existing); }
    public async Task DeleteRequestAsync(Guid id, CancellationToken ct = default) { await using var db = await Db(ct); var item = await db.SavedRequests.FindAsync([id], ct); if (item is not null) { db.SavedRequests.Remove(item); await db.SaveChangesAsync(ct); } }
    public async Task<SavedRestRequest> DuplicateRequestAsync(Guid id, CancellationToken ct = default) { await using var db = await Db(ct); var item = await db.SavedRequests.FindAsync([id], ct) ?? throw new InvalidOperationException("Saved request not found."); var copy = ToModel(item); copy.Id = Guid.NewGuid(); copy.Name += " Copy"; copy.UpdatedAt = DateTimeOffset.UtcNow; return await SaveRequestAsync(copy, ct); }
    public async Task MoveRequestAsync(Guid id, Guid collectionId, Guid? folderId, CancellationToken ct = default) { await using var db = await Db(ct); var item = await db.SavedRequests.FindAsync([id], ct) ?? throw new InvalidOperationException("Saved request not found."); item.CollectionId = collectionId; item.FolderId = folderId; item.UpdatedAt = DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); }
    public async Task<IReadOnlyList<SavedRestRequest>> SearchAsync(string query, CancellationToken ct = default) { await using var db = await Db(ct); query = query.Trim(); var items = db.SavedRequests.AsQueryable(); if (!string.IsNullOrWhiteSpace(query)) items = items.Where(x => x.Name.Contains(query) || x.Url.Contains(query) || x.Method.Contains(query)); return (await items.OrderBy(x => x.Name).Take(250).ToListAsync(ct)).Select(ToModel).ToArray(); }
    internal static RestCollection ToModel(CollectionEntity c, IEnumerable<CollectionFolderEntity> folders, IEnumerable<SavedRequestEntity> requests) => new() { Id = c.Id, Name = c.Name, Description = c.Description, SortOrder = c.SortOrder, CreatedAt = c.CreatedAt, UpdatedAt = c.UpdatedAt, Folders = folders.Select(x => new RestCollectionFolder { Id = x.Id, CollectionId = x.CollectionId, ParentFolderId = x.ParentFolderId, Name = x.Name, SortOrder = x.SortOrder, CreatedAt = x.CreatedAt, UpdatedAt = x.UpdatedAt }).ToList(), Requests = requests.Select(ToModel).ToList() };
    internal static SavedRestRequest ToModel(SavedRequestEntity x) => new() { Id = x.Id, CollectionId = x.CollectionId, FolderId = x.FolderId, Name = x.Name, Description = x.Description, Method = x.Method, Url = x.Url, Parameters = Deserialize(x.ParametersJson), Headers = Deserialize(x.HeadersJson), Body = x.Body, ContentType = x.ContentType, AuthType = x.AuthType, AuthToken = x.AuthToken, AuthUsername = x.AuthUsername, AuthPassword = x.AuthPassword, SortOrder = x.SortOrder, CreatedAt = x.CreatedAt, UpdatedAt = x.UpdatedAt };
    private static List<SavedRequestField> Deserialize(string text) { try { return JsonSerializer.Deserialize<List<SavedRequestField>>(text, Json) ?? []; } catch { return []; } }
    private static void Copy(SavedRestRequest x, SavedRequestEntity y) { y.CollectionId = x.CollectionId; y.FolderId = x.FolderId; y.Name = Required(x.Name, 240); y.Description = Trim(x.Description, 2000); y.Method = ValidMethod(x.Method); y.Url = Required(x.Url, 16000); y.ParametersJson = JsonSerializer.Serialize(x.Parameters, Json); y.HeadersJson = JsonSerializer.Serialize(x.Headers, Json); y.Body = x.Body ?? string.Empty; y.ContentType = x.ContentType ?? "application/json"; y.AuthType = x.AuthType ?? "None"; y.AuthToken = x.AuthToken; y.AuthUsername = x.AuthUsername; y.AuthPassword = x.AuthPassword; y.SortOrder = x.SortOrder; y.UpdatedAt = DateTimeOffset.UtcNow; }
    private static void Validate(SavedRestRequest x) { _ = Required(x.Name, 240); _ = Required(x.Url, 16000); _ = ValidMethod(x.Method); }
    private static string ValidMethod(string value) { var method = value.ToUpperInvariant(); return method is "GET" or "POST" or "PUT" or "PATCH" or "DELETE" or "HEAD" or "OPTIONS" ? method : throw new InvalidOperationException("Unsupported HTTP method."); }
    private static string Required(string? value, int max) { value = value?.Trim(); return !string.IsNullOrWhiteSpace(value) && value.Length <= max ? value : throw new InvalidOperationException("A required value is missing or too long."); }
    private static string? Trim(string? value, int max) => string.IsNullOrWhiteSpace(value) ? null : value.Trim().Length <= max ? value.Trim() : value.Trim()[..max];
}

public sealed class LocalEnvironmentService(IDbContextFactory<DeveloperBrowserDbContext> factory, ISecretStore secrets) : IEnvironmentService
{
    private async Task<DeveloperBrowserDbContext> Db(CancellationToken ct) { var db = await factory.CreateDbContextAsync(ct); await db.Database.EnsureCreatedAsync(ct); await CollectionSchema.EnsureAsync(db, ct); return db; }
    public async Task<IReadOnlyList<RestEnvironment>> GetEnvironmentsAsync(bool includeSecretValues = false, CancellationToken ct = default) { await using var db = await Db(ct); var environments = await db.Environments.OrderByDescending(x => x.IsActive).ThenBy(x => x.SortOrder).ThenBy(x => x.Name).ToListAsync(ct); var variables = await db.EnvironmentVariables.OrderBy(x => x.Key).ToListAsync(ct); var result = new List<RestEnvironment>(); foreach (var environment in environments) { var values = new List<RestEnvironmentVariable>(); foreach (var item in variables.Where(x => x.EnvironmentId == environment.Id)) values.Add(new() { Id = item.Id, EnvironmentId = item.EnvironmentId, Key = item.Key, Value = item.IsSecret && includeSecretValues ? await secrets.GetAsync(item.SecretStoreKey ?? SecretKey(item.Id), ct) : item.Value, Description = item.Description, IsSecret = item.IsSecret, IsEnabled = item.IsEnabled, CreatedAt = item.CreatedAt, UpdatedAt = item.UpdatedAt }); result.Add(new() { Id = environment.Id, Name = environment.Name, Description = environment.Description, Color = environment.Color, IsActive = environment.IsActive, SortOrder = environment.SortOrder, CreatedAt = environment.CreatedAt, UpdatedAt = environment.UpdatedAt, Variables = values }); } return result; }
    public async Task<RestEnvironment> CreateEnvironmentAsync(string name, string? description = null, string? color = null, bool makeActive = false, CancellationToken ct = default) { await using var db = await Db(ct); var hasExisting = await db.Environments.AnyAsync(ct); if (makeActive) foreach (var environment in await db.Environments.ToListAsync(ct)) environment.IsActive = false; var entity = new EnvironmentEntity { Name = Required(name), Description = description?.Trim(), Color = NormalizeColor(color), IsActive = makeActive || !hasExisting, SortOrder = await db.Environments.CountAsync(ct) }; db.Environments.Add(entity); await db.SaveChangesAsync(ct); return new() { Id = entity.Id, Name = entity.Name, Description = entity.Description, Color = entity.Color, IsActive = entity.IsActive, SortOrder = entity.SortOrder, CreatedAt = entity.CreatedAt, UpdatedAt = entity.UpdatedAt }; }
    public async Task RenameEnvironmentAsync(Guid id, string name, string? description, CancellationToken ct = default) { await using var db = await Db(ct); var entity = await db.Environments.FindAsync([id], ct) ?? throw new InvalidOperationException("Environment not found."); entity.Name = Required(name); entity.Description = description?.Trim(); entity.UpdatedAt = DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); }
    public async Task SetActiveAsync(Guid? id, CancellationToken ct = default) { await using var db = await Db(ct); var all = await db.Environments.ToListAsync(ct); foreach (var environment in all) { environment.IsActive = environment.Id == id; environment.UpdatedAt = DateTimeOffset.UtcNow; } await db.SaveChangesAsync(ct); }
    public async Task<RestEnvironment> DuplicateEnvironmentAsync(Guid id, CancellationToken ct = default) { var source = (await GetEnvironmentsAsync(true, ct)).SingleOrDefault(x => x.Id == id) ?? throw new InvalidOperationException("Environment not found."); var copy = await CreateEnvironmentAsync(source.Name + " Copy", source.Description, source.Color, false, ct); foreach (var value in source.Variables) await SaveVariableAsync(new() { EnvironmentId = copy.Id, Key = value.Key, Value = value.Value, Description = value.Description, IsSecret = value.IsSecret, IsEnabled = value.IsEnabled }, ct); return (await GetEnvironmentsAsync(false, ct)).Single(x => x.Id == copy.Id); }
    public async Task DeleteEnvironmentAsync(Guid id, CancellationToken ct = default) { await using var db = await Db(ct); var variables = await db.EnvironmentVariables.Where(x => x.EnvironmentId == id).ToListAsync(ct); foreach (var item in variables.Where(x => x.IsSecret)) await secrets.RemoveAsync(item.SecretStoreKey ?? SecretKey(item.Id), ct); db.EnvironmentVariables.RemoveRange(variables); var env = await db.Environments.FindAsync([id], ct); if (env is not null) db.Environments.Remove(env); await db.SaveChangesAsync(ct); }
    public async Task<RestEnvironmentVariable> SaveVariableAsync(RestEnvironmentVariable variable, CancellationToken ct = default) { await using var db = await Db(ct); var item = await db.EnvironmentVariables.FindAsync([variable.Id], ct); if (item is null) { item = new EnvironmentVariableEntity { Id = variable.Id, CreatedAt = variable.CreatedAt, Key = variable.Key }; db.EnvironmentVariables.Add(item); } item.EnvironmentId = variable.EnvironmentId; item.Key = Required(variable.Key); item.Description = variable.Description?.Trim(); item.IsSecret = variable.IsSecret; item.IsEnabled = variable.IsEnabled; item.UpdatedAt = DateTimeOffset.UtcNow; if (item.IsSecret) { item.SecretStoreKey = SecretKey(item.Id); item.Value = null; await secrets.SaveAsync(item.SecretStoreKey, variable.Value ?? string.Empty, ct); } else { if (!string.IsNullOrWhiteSpace(item.SecretStoreKey)) await secrets.RemoveAsync(item.SecretStoreKey, ct); item.SecretStoreKey = null; item.Value = variable.Value ?? string.Empty; } await db.SaveChangesAsync(ct); return new() { Id = item.Id, EnvironmentId = item.EnvironmentId, Key = item.Key, Value = item.IsSecret ? null : item.Value, Description = item.Description, IsSecret = item.IsSecret, IsEnabled = item.IsEnabled, CreatedAt = item.CreatedAt, UpdatedAt = item.UpdatedAt }; }
    public async Task DeleteVariableAsync(Guid id, CancellationToken ct = default) { await using var db = await Db(ct); var item = await db.EnvironmentVariables.FindAsync([id], ct); if (item is null) return; if (item.IsSecret) await secrets.RemoveAsync(item.SecretStoreKey ?? SecretKey(item.Id), ct); db.EnvironmentVariables.Remove(item); await db.SaveChangesAsync(ct); }
    private static string Required(string? value) { value = value?.Trim(); return !string.IsNullOrWhiteSpace(value) && value.Length <= 160 ? value : throw new InvalidOperationException("Environment names and variable keys are required."); }
    private static string SecretKey(Guid id) => "environment-variable:" + id;
    private static string NormalizeColor(string? color) => color is "#4ADE80" or "#60A5FA" or "#F87171" or "#FB923C" or "#A78BFA" or "#94A3B8" or "#F472B6" or "#FACC15" ? color : "#4ADE80";
}

internal static class CollectionSchema
{
    public static async Task EnsureAsync(DeveloperBrowserDbContext db, CancellationToken ct)
    {
        var sql = """
            CREATE TABLE IF NOT EXISTS Collections (Id TEXT NOT NULL PRIMARY KEY, Name TEXT NOT NULL, Description TEXT NULL, SortOrder INTEGER NOT NULL, CreatedAt TEXT NOT NULL, UpdatedAt TEXT NOT NULL);
            CREATE TABLE IF NOT EXISTS CollectionFolders (Id TEXT NOT NULL PRIMARY KEY, CollectionId TEXT NOT NULL, ParentFolderId TEXT NULL, Name TEXT NOT NULL, SortOrder INTEGER NOT NULL, CreatedAt TEXT NOT NULL, UpdatedAt TEXT NOT NULL);
            CREATE INDEX IF NOT EXISTS IX_CollectionFolders_CollectionId ON CollectionFolders (CollectionId);
            CREATE TABLE IF NOT EXISTS SavedRequests (Id TEXT NOT NULL PRIMARY KEY, CollectionId TEXT NOT NULL, FolderId TEXT NULL, Name TEXT NOT NULL, Description TEXT NULL, Method TEXT NOT NULL, Url TEXT NOT NULL, ParametersJson TEXT NOT NULL, HeadersJson TEXT NOT NULL, Body TEXT NOT NULL, ContentType TEXT NOT NULL, AuthType TEXT NOT NULL, AuthToken TEXT NULL, AuthUsername TEXT NULL, AuthPassword TEXT NULL, SortOrder INTEGER NOT NULL, CreatedAt TEXT NOT NULL, UpdatedAt TEXT NOT NULL);
            CREATE INDEX IF NOT EXISTS IX_SavedRequests_CollectionId ON SavedRequests (CollectionId);
            CREATE INDEX IF NOT EXISTS IX_SavedRequests_FolderId ON SavedRequests (FolderId);
            CREATE TABLE IF NOT EXISTS Environments (Id TEXT NOT NULL PRIMARY KEY, Name TEXT NOT NULL, Description TEXT NULL, SortOrder INTEGER NOT NULL, CreatedAt TEXT NOT NULL, UpdatedAt TEXT NOT NULL);
            CREATE TABLE IF NOT EXISTS EnvironmentVariables (Id TEXT NOT NULL PRIMARY KEY, EnvironmentId TEXT NOT NULL, Key TEXT NOT NULL, Value TEXT NULL, IsSecret INTEGER NOT NULL, SecretStoreKey TEXT NULL, CreatedAt TEXT NOT NULL, UpdatedAt TEXT NOT NULL);
            CREATE UNIQUE INDEX IF NOT EXISTS IX_EnvironmentVariables_EnvironmentId_Key ON EnvironmentVariables (EnvironmentId, Key);
            """;
        await db.Database.ExecuteSqlRawAsync(sql, ct);
        await AddColumnIfMissingAsync(db, "Environments", "IsActive", "INTEGER NOT NULL DEFAULT 0", ct);
        await AddColumnIfMissingAsync(db, "Environments", "Color", "TEXT NOT NULL DEFAULT '#4ADE80'", ct);
        await AddColumnIfMissingAsync(db, "EnvironmentVariables", "Description", "TEXT NULL", ct);
        await AddColumnIfMissingAsync(db, "EnvironmentVariables", "IsEnabled", "INTEGER NOT NULL DEFAULT 1", ct);
    }
    private static async Task AddColumnIfMissingAsync(DeveloperBrowserDbContext db, string table, string column, string definition, CancellationToken ct)
    {
        await using var command = db.Database.GetDbConnection().CreateCommand();
        if (command.Connection!.State != System.Data.ConnectionState.Open) await command.Connection.OpenAsync(ct);
        command.CommandText = $"PRAGMA table_info({table});";
        await using var reader = await command.ExecuteReaderAsync(ct);
        var exists = false;
        while (await reader.ReadAsync(ct)) if (string.Equals(reader.GetString(1), column, StringComparison.OrdinalIgnoreCase)) { exists = true; break; }
        await reader.CloseAsync();
        if (!exists)
        {
            var statement = (table, column) switch
            {
                ("Environments", "IsActive") => "ALTER TABLE Environments ADD COLUMN IsActive INTEGER NOT NULL DEFAULT 0;",
                ("Environments", "Color") => "ALTER TABLE Environments ADD COLUMN Color TEXT NOT NULL DEFAULT '#4ADE80';",
                ("EnvironmentVariables", "Description") => "ALTER TABLE EnvironmentVariables ADD COLUMN Description TEXT NULL;",
                ("EnvironmentVariables", "IsEnabled") => "ALTER TABLE EnvironmentVariables ADD COLUMN IsEnabled INTEGER NOT NULL DEFAULT 1;",
                _ => throw new InvalidOperationException("Unsupported local schema update.")
            };
            await db.Database.ExecuteSqlRawAsync(statement, ct);
        }
    }
}
